server:
  port: 8080
  error:
    include-stacktrace: on_trace_param

logging:
  level:
    root: WARN
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    se.iths.auktionera: INFO

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/auktionera
    username: root
    password: root






