server:
  port: 8080
  error:
    include-stacktrace: on_trace_param

logging:
  level:
    root: WARN
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
    se.iths.auktionera: INFO

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/auktionera
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 528021233727-868kei3rpsvjtjqifjqsus6vvrahl3co.apps.googleusercontent.com
            client-secret: HGe_ksHrvAkIQGdEC3Rfjzgh
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            #redirectUri: "{baseUrl}/oauth2/code/google"
            scope:
              - email
              - profile










